name: GitHub CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Check version
        run: |
          node --version
          yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Check formats
        run: yarn fmt --check

      - name: Build
        run: yarn build
